name: Test GitHub Action

on: 
  push:
    branches:
      - main  # This triggers the workflow when pushing to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: 23ds3000241@ds.study.iitm.ac.in
        run: echo "Hello, world!"
